In [1]:
import pandas as pd

In [2]:
import matplotlib.pyplot as plt

In [3]:
%matplotlib inline

In [4]:
ri=pd.read_csv('police.csv')

In [5]:
ri.head()

,stop_date,stop_time,county_name,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop
0,2005-01-02,01:55,NaN,M,1985.0,20.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
1,2005-01-18,08:15,NaN,M,1965.0,40.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
2,2005-01-23,23:15,NaN,M,1972.0,33.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
3,2005-02-20,17:15,NaN,M,1986.0,19.0,White,Call for Service,Other,False,NaN,Arrest Driver,True,16-30 Min,False
4,2005-03-14,10:00,NaN,F,1984.0,21.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False

In [6]:
ri.shape

(91741, 15)

In [8]:
ri.describe()

       county_name  driver_age_raw    driver_age
count          0.0    86414.000000  86120.000000
mean           NaN     1970.491228     34.011333
std            NaN      110.914909     12.738564
min            NaN        0.000000     15.000000
25%            NaN     1967.000000     23.000000
50%            NaN     1980.000000     31.000000
75%            NaN     1987.000000     43.000000
max            NaN     8801.000000     99.000000

In [9]:
ri.tail()

,stop_date,stop_time,county_name,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop
91736,2015-12-31,20:27,NaN,M,1986.0,29.0,White,Speeding,Speeding,False,NaN,Warning,False,0-15 Min,False
91737,2015-12-31,20:35,NaN,F,1982.0,33.0,White,Equipment/Inspection Violation,Equipment,False,NaN,Warning,False,0-15 Min,False
91738,2015-12-31,20:45,NaN,M,1992.0,23.0,White,Other Traffic Violation,Moving violation,False,NaN,Warning,False,0-15 Min,False
91739,2015-12-31,21:42,NaN,M,1993.0,22.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
91740,2015-12-31,22:46,NaN,M,1959.0,56.0,Hispanic,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False

In [11]:
ri.isnull().sum()

stop_date                 0
stop_time                 0
county_name           91741
driver_gender          5335
driver_age_raw         5327
driver_age             5621
driver_race            5333
violation_raw          5333
violation              5333
search_conducted          0
search_type           88545
stop_outcome           5333
is_arrested            5333
stop_duration          5333
drugs_related_stop        0
dtype: int64

In [13]:
ri.drop('county_name', axis=1, inplace=True)

,stop_date,stop_time,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop
0,2005-01-02,01:55,M,1985.0,20.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
1,2005-01-18,08:15,M,1965.0,40.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
2,2005-01-23,23:15,M,1972.0,33.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
3,2005-02-20,17:15,M,1986.0,19.0,White,Call for Service,Other,False,NaN,Arrest Driver,True,16-30 Min,False
4,2005-03-14,10:00,F,1984.0,21.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
5,2005-03-23,09:45,M,1982.0,23.0,Black,Equipment/Inspection Violation,Equipment,False,NaN,Citation,False,0-15 Min,False
6,2005-04-01,17:30,M,1969.0,36.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
7,2005-06-06,13:20,F,1986.0,19.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
8,2005-07-13,10:15,M,1970.0,35.0,Black,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
9,2005-07-13,15:45,M,1970.0,35.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
10,2005-07-13,16:20,M,1979.0,26.0,Asian,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
11,2005-07-13,19:00,F,1966.0,39.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
12,2005-07-14,19:55,M,1979.0,26.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
13,2005-07-18,19:30,F,1984.0,21.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
14,2005-07-18,19:45,M,1969.0,36.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
15,2005-07-19,00:30,M,1982.0,23.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
16,2005-07-19,00:30,M,1982.0,23.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
17,2005-07-19,23:30,M,1979.0,26.0,White,Equipment/Inspection Violation,Equipment,False,NaN,Citation,False,0-15 Min,False
18,2005-07-20,00:05,M,1955.0,50.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
19,2005-07-24,20:10,F,1958.0,47.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
20,2005-07-28,12:37,F,1979.0,26.0,Asian,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
21,2005-08-07,16:50,M,1953.0,52.0,White,Other Traffic Violation,Moving violation,False,NaN,Citation,False,0-15 Min,False
22,2005-08-08,02:09,M,1955.0,50.0,Black,Other Traffic Violation,Moving violation,False,NaN,Arrest Driver,True,30+ Min,False
23,2005-08-18,10:57,F,1967.0,38.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
24,2005-08-28,01:00,M,1979.0,26.0,White,Other Traffic Violation,Moving violation,True,"Incident to Arrest,Protective Frisk",Arrest Driver,True,16-30 Min,False
25,2005-09-03,16:02,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,False
26,2005-09-17,10:54,M,1964.0,41.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
27,2005-09-21,13:30,F,1977.0,28.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
28,2005-09-22,22:34,M,1984.0,21.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
29,2005-09-26,01:05,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91711,2015-12-30,15:42,M,1974.0,41.0,White,Speeding,Speeding,False,NaN,Citation,False,16-30 Min,False
91712,2015-12-30,16:19,F,1989.0,26.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
91713,2015-12-30,17:07,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,False
91714,2015-12-30,17:39,M,1996.0,19.0,Hispanic,Speeding,Speeding,False,NaN,Citation,False,16-30 Min,False
91715,2015-12-30,23:26,F,1994.0,21.0,Hispanic,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
91716,2015-12-30,23:33,F,1983.0,32.0,Hispanic,Seatbelt Violation,Seat belt,False,NaN,Citation,False,0-15 Min,False
91717,2015-12-31,00:00,F,1993.0,22.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
91718,2015-12-31,00:01,M,1966.0,49.0,White,Other Traffic Violation,Moving violation,False,NaN,Citation,False,0-15 Min,False
91719,2015-12-31,06:31,M,1989.0,26.0,White,Other Traffic Violation,Moving violation,False,NaN,Citation,False,0-15 Min,False
91720,2015-12-31,06:32,M,1975.0,40.0,White,Speeding,Speeding,False,NaN,Citation,False,16-30 Min,False
91721,2015-12-31,06:49,M,1943.0,72.0,White,Speeding,Speeding,False,NaN,Warning,False,0-15 Min,False
91722,2015-12-31,07:06,M,1970.0,45.0,Black,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
91723,2015-12-31,07:14,M,1978.0,37.0,Hispanic,Registration Violation,Registration/plates,False,NaN,Citation,False,0-15 Min,False
91724,2015-12-31,07:27,M,1997.0,18.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
91725,2015-12-31,08:14,F,1960.0,55.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
91726,2015-12-31,08:41,M,1992.0,23.0,White,Speeding,Speeding,False,NaN,No Action,False,0-15 Min,False
91727,2015-12-31,09:17,F,1995.0,20.0,White,Speeding,Speeding,False,NaN,Warning,False,16-30 Min,False
91728,2015-12-31,13:50,F,1982.0,33.0,Hispanic,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
91729,2015-12-31,14:21,F,1988.0,27.0,White,Equipment/Inspection Violation,Equipment,False,NaN,Citation,False,0-15 Min,False
91730,2015-12-31,15:36,F,1996.0,19.0,Hispanic,Equipment/Inspection Violation,Equipment,False,NaN,Warning,False,0-15 Min,False
91731,2015-12-31,16:38,F,1988.0,27.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
91732,2015-12-31,19:44,F,1969.0,46.0,White,Speeding,Speeding,False,NaN,Warning,False,0-15 Min,False
91733,2015-12-31,19:55,F,1974.0,41.0,White,Registration Violation,Registration/plates,False,NaN,Citation,False,0-15 Min,False
91734,2015-12-31,20:20,M,1993.0,22.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
91735,2015-12-31,20:25,M,1992.0,23.0,Hispanic,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
91736,2015-12-31,20:27,M,1986.0,29.0,White,Speeding,Speeding,False,NaN,Warning,False,0-15 Min,False
91737,2015-12-31,20:35,F,1982.0,33.0,White,Equipment/Inspection Violation,Equipment,False,NaN,Warning,False,0-15 Min,False
91738,2015-12-31,20:45,M,1992.0,23.0,White,Other Traffic Violation,Moving violation,False,NaN,Warning,False,0-15 Min,False
91739,2015-12-31,21:42,M,1993.0,22.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
91740,2015-12-31,22:46,M,1959.0,56.0,Hispanic,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False

In [14]:
ri.columns

Index(['stop_date', 'stop_time', 'county_name', 'driver_gender',
       'driver_age_raw', 'driver_age', 'driver_race', 'violation_raw',
       'violation', 'search_conducted', 'search_type', 'stop_outcome',
       'is_arrested', 'stop_duration', 'drugs_related_stop'],
      dtype='object')

In [17]:
ri[ri['violation']=='Speeding'].driver_gender.value_counts()

M    32979
F    15482
Name: driver_gender, dtype: int64

In [18]:
df = pd.read_csv('https://query.data.world/s/e6ktfojmmwoczxfdmqmid2gvyntdo6')

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa8 in position 7: invalid start byte

In [19]:
import pandas as pd

In [20]:
df = pd.read_csv('https://query.data.world/s/e6ktfojmmwoczxfdmqmid2gvyntdo6')

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa8 in position 7: invalid start byte

In [21]:
pwd

'/Users/onlyone/Documents/Springboard'

In [22]:
cd Downloads

[Errno 2] No such file or directory: 'Downloads'
/Users/onlyone/Documents/Springboard

In [23]:
..

SyntaxError: invalid syntax (<ipython-input-23-3d80792ead7e>, line 1)

In [24]:
cd ..

/Users/onlyone/Documents

In [25]:
cd ..

/Users/onlyone

In [26]:
cd Downloads

/Users/onlyone/Downloads

In [28]:
df = pd.read_csv("gtd1993_748.csv", mode='r')

TypeError: parser_f() got an unexpected keyword argument 'mode'

In [29]:
ls

56C7EB461724646F9202EF913F7D8528803E582783EE5D8F77A77286016BF42677785AA084A7CE07CC081224B00C33AF.pdf
9781461409526-c1.pdf
AYSE TAS (1).docx
AYSE TAS.docx
CV_Huseyin YILMAZ.docx
GitHub Desktop.app/
Kings/
RESUME Mehmet Umut CAKIR 2018.docx
TIV-Export-Top-50-2000-2017.csv
ch1_slides.pdf
ch2_slides.pdf
ch3_slides.pdf
ch4_slides.pdf
chapter5.pdf
ehliyet/
gtd1993_748.csv
pep8.pdf
pycon-2018-tutorial-master/

In [30]:
gtd1993_748.csv

NameError: name 'gtd1993_748' is not defined

In [31]:
gtd1993_748.csv/

SyntaxError: invalid syntax (<ipython-input-31-9259eb071e25>, line 1)

In [32]:
/gtd1993_748.csv

NameError: name 'gtd1993_748' is not defined

In [33]:
AYSE TAS.docx

SyntaxError: invalid syntax (<ipython-input-33-625969166a5f>, line 1)

In [34]:
/AYSE TAS.docx

NameError: name 'AYSE' is not defined

In [35]:
"AYSE TAS.docx"

'AYSE TAS.docx'

In [36]:
cd ..

/Users/onlyone

In [37]:
documents

NameError: name 'documents' is not defined

In [38]:
Documents

NameError: name 'Documents' is not defined

In [39]:
ls

Applications/           Movies/                 anaconda3/
Desktop/                Music/                  deneme_1.ipynb
Documents/              Pictures/               iCloud Drive (Archive)/
Downloads/              Public/                 newwnew/
Library/                Untitled.ipynb

In [40]:
cd Documents

/Users/onlyone/Documents

In [41]:
cd data

/Users/onlyone/Documents/data

In [42]:
ls

chipotle.tsv.html       imdb_1000.csv.html      titanic_train.csv.html
drinks.csv.html         titanic.csv
gtd1993_748.csv         titanic_test.csv.html

In [43]:
q = pd.read_csv('gtd1993_748.csv')

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa8 in position 7: invalid start byte